Repository TurnerSoftware/CacheTower, pull requests merged in 2021-08, with the labels that each got.

#178 Fix issues with `RedisRemoteEviction` on new cache items
  benchmarks/CacheTower.Benchmarks/Extensions/BaseCacheChangeExtensionBenchmark.cs
  src/CacheTower.Extensions.Redis/RedisRemoteEvictionExtension.cs
  src/CacheTower/CacheStack.cs
  src/CacheTower/Extensions/ExtensionContainer.cs
  src/CacheTower/ICacheExtension.cs
  tests/CacheTower.Tests/CacheStackTests.cs
  tests/CacheTower.Tests/Extensions/ExtensionContainerTests.cs
  tests/CacheTower.Tests/Extensions/Redis/RedisRemoteEvictionExtensionTests.cs
Labels: bug

#182 Make sure subscriptions are cleared on ResetState
  tests/CacheTower.Tests/Utils/RedisHelper.cs
Labels: enhancement

#184 Add busy lock support for `RedisLockExtension`
  src/CacheTower.Extensions.Redis/RedisLockExtension.cs
  src/CacheTower.Extensions.Redis/RedisLockOptions.cs
  src/CacheTower/CacheStack.cs
  tests/CacheTower.Tests/Extensions/Redis/RedisLockExtensionTests.cs
Labels: enhancement

#188 Fix file manifest load issues
  src/CacheTower/Providers/FileSystem/FileCacheLayerBase.cs
  tests/CacheTower.Tests/Providers/BaseCacheLayerTests.cs
  tests/CacheTower.Tests/Providers/FileSystem/Json/JsonFileCacheLayerTests.cs
  tests/CacheTower.Tests/Providers/FileSystem/Protobuf/ProtobufFileCacheLayerTests.cs
Labels: bugfix
